# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/paulg/projects/Apagnan

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/paulg/projects/Apagnan

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/paulg/projects/Apagnan/CMakeFiles /home/paulg/projects/Apagnan//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/paulg/projects/Apagnan/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Apagnan

# Build rule for target.
Apagnan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Apagnan
.PHONY : Apagnan

# fast build rule for target.
Apagnan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Apagnan.dir/build.make CMakeFiles/Apagnan.dir/build
.PHONY : Apagnan/fast

sources/logger/logger.o: sources/logger/logger.cpp.o
.PHONY : sources/logger/logger.o

# target to build an object file
sources/logger/logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Apagnan.dir/build.make CMakeFiles/Apagnan.dir/sources/logger/logger.cpp.o
.PHONY : sources/logger/logger.cpp.o

sources/logger/logger.i: sources/logger/logger.cpp.i
.PHONY : sources/logger/logger.i

# target to preprocess a source file
sources/logger/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Apagnan.dir/build.make CMakeFiles/Apagnan.dir/sources/logger/logger.cpp.i
.PHONY : sources/logger/logger.cpp.i

sources/logger/logger.s: sources/logger/logger.cpp.s
.PHONY : sources/logger/logger.s

# target to generate assembly for a file
sources/logger/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Apagnan.dir/build.make CMakeFiles/Apagnan.dir/sources/logger/logger.cpp.s
.PHONY : sources/logger/logger.cpp.s

sources/main.o: sources/main.cpp.o
.PHONY : sources/main.o

# target to build an object file
sources/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Apagnan.dir/build.make CMakeFiles/Apagnan.dir/sources/main.cpp.o
.PHONY : sources/main.cpp.o

sources/main.i: sources/main.cpp.i
.PHONY : sources/main.i

# target to preprocess a source file
sources/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Apagnan.dir/build.make CMakeFiles/Apagnan.dir/sources/main.cpp.i
.PHONY : sources/main.cpp.i

sources/main.s: sources/main.cpp.s
.PHONY : sources/main.s

# target to generate assembly for a file
sources/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Apagnan.dir/build.make CMakeFiles/Apagnan.dir/sources/main.cpp.s
.PHONY : sources/main.cpp.s

sources/server/request.o: sources/server/request.cpp.o
.PHONY : sources/server/request.o

# target to build an object file
sources/server/request.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Apagnan.dir/build.make CMakeFiles/Apagnan.dir/sources/server/request.cpp.o
.PHONY : sources/server/request.cpp.o

sources/server/request.i: sources/server/request.cpp.i
.PHONY : sources/server/request.i

# target to preprocess a source file
sources/server/request.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Apagnan.dir/build.make CMakeFiles/Apagnan.dir/sources/server/request.cpp.i
.PHONY : sources/server/request.cpp.i

sources/server/request.s: sources/server/request.cpp.s
.PHONY : sources/server/request.s

# target to generate assembly for a file
sources/server/request.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Apagnan.dir/build.make CMakeFiles/Apagnan.dir/sources/server/request.cpp.s
.PHONY : sources/server/request.cpp.s

sources/server/server.o: sources/server/server.cpp.o
.PHONY : sources/server/server.o

# target to build an object file
sources/server/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Apagnan.dir/build.make CMakeFiles/Apagnan.dir/sources/server/server.cpp.o
.PHONY : sources/server/server.cpp.o

sources/server/server.i: sources/server/server.cpp.i
.PHONY : sources/server/server.i

# target to preprocess a source file
sources/server/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Apagnan.dir/build.make CMakeFiles/Apagnan.dir/sources/server/server.cpp.i
.PHONY : sources/server/server.cpp.i

sources/server/server.s: sources/server/server.cpp.s
.PHONY : sources/server/server.s

# target to generate assembly for a file
sources/server/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Apagnan.dir/build.make CMakeFiles/Apagnan.dir/sources/server/server.cpp.s
.PHONY : sources/server/server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Apagnan"
	@echo "... sources/logger/logger.o"
	@echo "... sources/logger/logger.i"
	@echo "... sources/logger/logger.s"
	@echo "... sources/main.o"
	@echo "... sources/main.i"
	@echo "... sources/main.s"
	@echo "... sources/server/request.o"
	@echo "... sources/server/request.i"
	@echo "... sources/server/request.s"
	@echo "... sources/server/server.o"
	@echo "... sources/server/server.i"
	@echo "... sources/server/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

